### ISSUE TITLE
Add an Explanation for The Slope of a Line

### ISSUE THREAD

**Issue by Kyle-Pu** [Kyle-Pu/Mathematics#19]
# Issue Templates
Please add a SlopeOfALineExplanation.md file discussing the concept of the slope of a line as well as the equation, how to use it, etc. Be sure to include undefined slopes, 0 slopes, etc in your explanations. 

An example of a well-done explanation file can be found at https://github.com/Kyle-P/Mathematics/blob/master/Geometry/HeronExplanation.md.

Thanks!

**Comment by manimanasamylavarapu** [comment]
Please assign this to me

**Comment by manimanasamylavarapu** [comment]
There is already one explanation file for this which you have added. So what more is expected

**Comment by Kyle-Pu** [comment]
Thanks for pointing this out @manimanasamylavarapu. I'll close this issue.
