### ISSUE TITLE
Add a "Using Our Program" Section in Heron's Program

### ISSUE THREAD

**Issue by Kyle-Pu** [Kyle-Pu/Mathematics#30]
Background: Each explanation file should include a "Using Our Program" section as detailed in CONTRIBUTING.md. 

Please add a "Using Our Program" section in the [Heron Explanation README](https://github.com/Kyle-P/Mathematics/blob/master/Geometry/Heron/HeronExplanation.md). Good template to follow: https://github.com/Kyle-P/Mathematics/blob/master/Algebra/SlopeOfALineExplanation.md

**Comment by declansullivan** [comment]
Submitted a pull request relating to this, feel free to check it out!
