### ISSUE TITLE
Branch Creation Access

### ISSUE THREAD

**Issue by jwheeler31** [Kyle-Pu/Mathematics#72]
@Kyle-Pu, I spent the time to start setting up a proper build architecture on a separate branch, but rights aren't available to create a branch. Is this the desired behavior?

**Comment by Kyle-Pu** [comment]
Thanks so much, @jwheeler31. Could you please let me know where I can find the settings to enable that? Thanks for contributing to this project!

**Comment by jwheeler31** [comment]
This is the "protecting" of branches - I'd assume it's just the reverse. https://help.github.com/en/articles/enabling-branch-restrictions

**Comment by zhenpeng-indeed** [comment]
@jwheeler31 you can fork the repo and work on your repo, then merge the branch in your repo back to this repo.
